# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from thinkagain.backends.grpc.proto import replica_pb2 as thinkagain_dot_distributed_dot_grpc_dot_proto_dot_replica__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in thinkagain/distributed/grpc/proto/replica_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicaServiceStub(object):
    """Service for executing replicated functions remotely
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/thinkagain.distributed.grpc.ReplicaService/Execute',
                request_serializer=thinkagain_dot_distributed_dot_grpc_dot_proto_dot_replica__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=thinkagain_dot_distributed_dot_grpc_dot_proto_dot_replica__pb2.ExecuteResponse.FromString,
                _registered_method=True)


class ReplicaServiceServicer(object):
    """Service for executing replicated functions remotely
    """

    def Execute(self, request, context):
        """Execute a function call on the replica
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=thinkagain_dot_distributed_dot_grpc_dot_proto_dot_replica__pb2.ExecuteRequest.FromString,
                    response_serializer=thinkagain_dot_distributed_dot_grpc_dot_proto_dot_replica__pb2.ExecuteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'thinkagain.distributed.grpc.ReplicaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('thinkagain.distributed.grpc.ReplicaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReplicaService(object):
    """Service for executing replicated functions remotely
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/thinkagain.distributed.grpc.ReplicaService/Execute',
            thinkagain_dot_distributed_dot_grpc_dot_proto_dot_replica__pb2.ExecuteRequest.SerializeToString,
            thinkagain_dot_distributed_dot_grpc_dot_proto_dot_replica__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
