# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: thinkagain/distributed/grpc/proto/replica.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'thinkagain/distributed/grpc/proto/replica.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/thinkagain/distributed/grpc/proto/replica.proto\x12\x1bthinkagain.distributed.grpc\"\x1e\n\x0e\x45xecuteRequest\x12\x0c\n\x04\x61rgs\x18\x01 \x01(\x0c\"0\n\x0f\x45xecuteResponse\x12\x0e\n\x06result\x18\x01 \x01(\x0c\x12\r\n\x05\x65rror\x18\x02 \x01(\t2v\n\x0eReplicaService\x12\x64\n\x07\x45xecute\x12+.thinkagain.distributed.grpc.ExecuteRequest\x1a,.thinkagain.distributed.grpc.ExecuteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thinkagain.distributed.grpc.proto.replica_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXECUTEREQUEST']._serialized_start=80
  _globals['_EXECUTEREQUEST']._serialized_end=110
  _globals['_EXECUTERESPONSE']._serialized_start=112
  _globals['_EXECUTERESPONSE']._serialized_end=160
  _globals['_REPLICASERVICE']._serialized_start=162
  _globals['_REPLICASERVICE']._serialized_end=280
# @@protoc_insertion_point(module_scope)
